import { Navbar } from '@/components/Navbar'
import Head from "next/head";
import {Card} from "@/components/Card";
const ProjectPage2: React.FC = () => {
    return (
        <>
            <Head>
                <title>Root/Projects</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar/>
            <Card header="Quincy's SCP Party" link="https://quincyscp.gq/" picture="/images/duckfavicon192.png" width={160}>
        </Card>
            </>
    )
}
export default ProjectPage2;