import { Navbar } from '@/components/Navbar'
import Head from "next/head";
import { Card } from "@/components/Card";
const ProjectPage1: React.FC = () => {
    return (
        <>
            <Head>
                <title>Root/Projects</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar prop='text-center fixed z-10 w-full h-24 bg-Black flex items-center justify-center font-UbuntuMono text-White border-b-4 border-OpenClosing shadow-2xl text-2xl l:text-3xl' color="m-4" color1="text-OpenClosing  m-4" color2="m-4"/>
            <Card header="DeltaTime - Discord Bot" link="https://github.com/ZirixCZ/DeltaTime-Discord" picture="/images/deltatime.png" width={150}>
            </Card>
        </>
    )
}
export default ProjectPage1;