import { Navbar } from '@/components/Navbar'
import Head from "next/head";
import { Card } from "@/components/Card";
const ProjectPage2: React.FC = () => {
    return (
        <>
            <Head>
                <title>Root/Projects</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar prop='text-center fixed z-10 w-full h-24 bg-Black flex items-center justify-center font-UbuntuMono text-White border-b-2 border-Green shadow-2xl text-2xl l:text-3xl' color="m-4" color1="MainColorTheme  m-4" color2="m-4" />
            <Card header="Quincy's SCP Party" link="https://quincyscp.gq/" picture="/images/duckfavicon192.png" width={160}>
            </Card>
        </>
    )
}
export default ProjectPage2;