import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { Navbar } from '@/components/Navbar';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Root</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
        <div className="bg-image h-screen w-screen bg-cover fixed"></div>
          <div className="w-full h-screen flex justify-center items-center flex-col font-UbuntuMono">

              <h1 className="animate__animated animate__bounce text-OpenClosing text-5xl 2xl:text-9xl mb-10 flex items-center z-10"><span className="text-OpenClosing font-bold">&lt;</span><span className="text-HTMLTag font-bold">h1</span><span className="text-OpenClosing font-bold">&gt;</span>Hello,<span className="text-OpenClosing font-bold">&lt;</span><span className="text-HTMLTag font-bold">/h1</span><span className="text-OpenClosing font-bold">&gt;</span></h1>
                  <h2 className="text-White text-2xl 2xl:text-5xl mb-10 text-OpenClosing z-10 text-center"><span className="text-OpenClosing font-bold">&lt;</span><span className="text-HTMLTag font-bold">h2</span><span className="text-OpenClosing font-bold">&gt;</span>I am a high school student. Check out my work.<span className="text-OpenClosing font-bold">&lt;</span><span className="text-HTMLTag font-bold">/h2</span><span className="text-OpenClosing font-bold">&gt;</span></h2>
                  <Link href="projects"><a className="bg-White text-DarkPurple border border-text-WhiteFont py-8 px-11 2xl:px-24 rounded-2xl text-3xl z-10">Let's Check it out!</a></Link>
          </div>
</>
  )
}

export default Home
