import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { Navbar } from '@/components/Navbar';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Root</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar prop='text-center fixed z-10 w-full h-24 bg-NavBar flex items-center justify-center font-UbuntuMono text-White border-b-2 border-HTMLTag shadow-2xl text-2xl l:text-3xl'/>
        <div className="fixed w-screen h-screen bg-cover bg-image"></div>
          <div className="flex flex-col justify-center items-center w-full h-screen font-UbuntuMono">

              <h1 className="flex z-10 items-center mb-10 text-4xl xl:text-5xl animate__animated animate__bounce text-OpenClosing 2xl:text-8xl xl:tracking-wide"><span className="font-bold text-OpenClosing">&lt;</span><span className="font-bold text-HTMLTag">h1</span><span className="font-bold text-OpenClosing">&gt;</span>Hello,<span className="font-bold text-OpenClosing">&lt;</span><span className="font-bold text-HTMLTag">/h1</span><span className="font-bold text-OpenClosing">&gt;</span></h1>
                  <h2 className="z-10 mx-4 mb-10 text-xl text-center text-White xl:text-4xl text-OpenClosing xl:tracking-wide"><span className="font-bold text-OpenClosing">&lt;</span><span className="font-bold text-HTMLTag">h2</span><span className="font-bold text-OpenClosing">&gt;</span>I am a high school student. Check out my work.<span className="font-bold text-OpenClosing">&lt;</span><span className="font-bold text-HTMLTag">/h2</span><span className="font-bold text-OpenClosing">&gt;</span></h2>
                  <Link href="projects"><a className="z-10 px-11 xl:py-5 py-6 text-2xl rounded-lg border xl:text-2xl bg-White text-DarkPurple border-text-WhiteFont 2xl:px-20 xl:tracking-widest">Let's Check it out!</a></Link>
          </div>
</>
  )
}

export default Home
