import { Navbar } from '@/components/Navbar'
import { useRouter } from 'next/router';
import { Item } from '@/components/Item'
import Head from "next/head";
const Projects: React.FC = () => {
    return (
        <>
            <Head>
                <title>Root/Projects</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        <Navbar/>
                <h2 className="text-center py-40 pb-0 text-6xl xl:text-8xl text-White font-bold">Projects</h2> 
            

                <h5 className="text-center m-20 text-White text-4xl">Github Projects</h5>
            <Item link="/projects/deltatime" header="DeltaTime" picture="/images/Octocat.png" width="96"/>
            <h5 className="text-center m-20 text-White text-4xl">Websites</h5>
            <Item link="https://quincyscp.gq/" header="Quincy's SL" picture="/images/duckfavicon192.png" width="80"/>
            <Item link="https://quincyet.ga/" header="Quincy's ET" picture="/images/duckfavicon192.png" width="80"/>
        </>
    )
}
export default Projects;